/**
 * HTML 내보내기 테스트
 */
import { describe, it, expect } from 'vitest';
import { generateHtml } from '../../../../src/core/export/html-exporter.js';
import type { ParsedSpec } from '../../../../src/core/export/schemas.js';

describe('html-exporter', () => {
  const sampleSpec: ParsedSpec = {
    id: 'auth',
    title: '사용자 인증',
    status: 'draft',
    version: '1.0.0',
    created: '2025-12-24',
    author: 'developer',
    description: 'JWT 기반 인증 시스템',
    requirements: [
      {
        id: 'REQ-001',
        title: '로그인',
        description: '시스템은 이메일/비밀번호 로그인을 지원해야 한다',
        keyword: 'SHALL',
        priority: 'high',
      },
      {
        id: 'REQ-002',
        title: '로그아웃',
        description: '시스템은 로그아웃을 지원해야 한다',
        keyword: 'SHOULD',
        priority: 'medium',
      },
    ],
    scenarios: [
      {
        id: 'scenario-1',
        title: '성공적인 로그인',
        given: ['유효한 사용자 계정이 있을 때'],
        when: ['올바른 이메일과 비밀번호로 로그인하면'],
        then: ['JWT 토큰이 반환된다'],
        and: ['토큰 만료 시간이 설정된다'],
      },
    ],
    dependencies: ['database'],
    metadata: { id: 'auth', title: '사용자 인증' },
    rawContent: '# 사용자 인증',
  };

  describe('generateHtml', () => {
    it('유효한 HTML을 생성한다', () => {
      const html = generateHtml([sampleSpec]);

      expect(html).toContain('<!DOCTYPE html>');
      expect(html).toContain('<html lang="ko">');
      expect(html).toContain('</html>');
    });

    it('제목을 포함한다', () => {
      const html = generateHtml([sampleSpec], { title: 'SDD 스펙 문서' });

      expect(html).toContain('<title>SDD 스펙 문서</title>');
      expect(html).toContain('<h1>SDD 스펙 문서</h1>');
    });

    it('메타데이터를 표시한다', () => {
      const html = generateHtml([sampleSpec]);

      expect(html).toContain('draft');
      expect(html).toContain('1.0.0');
      expect(html).toContain('2025-12-24');
      expect(html).toContain('developer');
    });

    it('요구사항을 표시한다', () => {
      const html = generateHtml([sampleSpec]);

      expect(html).toContain('REQ-001');
      expect(html).toContain('로그인');
      expect(html).toContain('REQ-002');
      expect(html).toContain('로그아웃');
    });

    it('시나리오를 표시한다', () => {
      const html = generateHtml([sampleSpec]);

      expect(html).toContain('scenario-1');
      expect(html).toContain('성공적인 로그인');
      expect(html).toContain('GIVEN');
      expect(html).toContain('WHEN');
      expect(html).toContain('THEN');
      expect(html).toContain('AND');
    });

    it('목차를 생성한다', () => {
      const html = generateHtml([sampleSpec], { includeToc: true });

      expect(html).toContain('class="toc"');
      expect(html).toContain('목차');
      expect(html).toContain('href="#REQ-001"');
    });

    it('목차를 제외할 수 있다', () => {
      const html = generateHtml([sampleSpec], { includeToc: false });

      expect(html).not.toContain('class="toc"');
    });

    it('라이트 테마를 적용한다', () => {
      const html = generateHtml([sampleSpec], { theme: 'light' });

      expect(html).toContain('--bg-color: #ffffff');
    });

    it('다크 테마를 적용한다', () => {
      const html = generateHtml([sampleSpec], { theme: 'dark' });

      expect(html).toContain('--bg-color: #1a1a2e');
    });

    it('RFC 2119 키워드를 강조한다', () => {
      const html = generateHtml([sampleSpec]);

      expect(html).toContain('rfc-keyword');
    });

    it('여러 스펙을 병합한다', () => {
      const spec2: ParsedSpec = {
        ...sampleSpec,
        id: 'profile',
        title: '프로필',
        requirements: [],
        scenarios: [],
      };

      const html = generateHtml([sampleSpec, spec2]);

      expect(html).toContain('사용자 인증');
      expect(html).toContain('프로필');
    });

    it('푸터를 포함한다', () => {
      const html = generateHtml([sampleSpec]);

      expect(html).toContain('Generated by SDD Tool');
    });
  });
});
